### ISSUE TITLE
Wrong `isSchoolHolidays` on school holidays' eve

### ISSUE THREAD

**Issue by MaelFr** [tataille/node-red-french-holidays#20]
Hello,

Every school holidays' eve, data show `isSchoolHolidays: true`.

For exemple today :
```
academy: Nantes
day: 5
isPublicHoliday: false
isSchoolHolidays: true           <== here is the problem
isTomorrowPublicHoliday: false
isTomorrowSchoolHolidays: true
nextPublicHolidayDate: 14/07/2025
nextPublicHolidayName: 14 juillet
nextSchoolHolidaysCoutdownInDays: -1
region: Métropole
schoolHolidaysEndDate: 29/08/2025
schoolHolidaysName: Vacances d'Été
schoolPeriod: 2024-2025
version: 1.2.5
year: 2025
zones: Zone B
friendly_name: frenchDaysData
```

My flow (copy/pasted from the README) :
```
[
    {
        "id": "ee7966d41a4eb93a",
        "type": "inject",
        "z": "f6f2187d.f17ca8",
        "g": "cacfee76aa1b857a",
        "name": "",
        "props": [],
        "repeat": "",
        "crontab": "05 01 * * *",
        "once": true,
        "onceDelay": "10",
        "topic": "",
        "x": 220,
        "y": 140,
        "wires": [
            [
                "6cde5e23f714597e"
            ]
        ]
    },
    {
        "id": "6cde5e23f714597e",
        "type": "french-holidays",
        "z": "f6f2187d.f17ca8",
        "g": "cacfee76aa1b857a",
        "name": "French Holidays",
        "academy": "Nantes",
        "geo": "Métropole",
        "x": 480,
        "y": 140,
        "wires": [
            [
                "01ec34062393567a"
            ]
        ]
    },
    {
        "id": "01ec34062393567a",
        "type": "mqtt out",
        "z": "f6f2187d.f17ca8",
        "g": "cacfee76aa1b857a",
        "name": "",
        "topic": "home/holidays",
        "qos": "1",
        "retain": "true",
        "respTopic": "",
        "contentType": "application/json",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "fe7e6333bdb83cdb",
        "x": 720,
        "y": 140,
        "wires": []
    },
    {
        "id": "fe7e6333bdb83cdb",
        "type": "mqtt-broker",
        "name": "MQTT server",
        "broker": "ip-address",
        "port": "123456",
        "clientid": "clientid",
        "autoConnect": true,
        "usetls": false,
        "protocolVersion": "5",
        "keepalive": "60",
        "cleansession": true,
        "autoUnsubscribe": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "willMsg": {},
        "userProps": "",
        "sessionExpiry": ""
    }
]
```

Versions : 
- `node-red@4.0.3`
- `@tataille/node-red-french-holidays@1.2.5`

**Comment by tataille** [comment]
Hi @MaelFr , I cannot reproduce the issue. I added a test  and the school holidays eve is correct. Can you give us more details (request date/time,...)

**Comment by MaelFr** [comment]
The flow runs every day at 1:05 am (`"crontab": "05 01 * * *",`), and this example is from July 4th, but it happens every day before a holiday.
Neither was I able to reproduce the issue, I think i tried the same tests as you.

**Comment by tataille** [comment]
Issue reproduced. Fix pushed, waiting for confirmation before new version. Thanks

**Comment by tataille** [comment]
Fix in version 1.2.6

**Comment by MaelFr** [comment]
Perfect.
Just, I think you forgot to comment out `french-holidays/french-holidays.js:94` when deleting the `console.log`.

**Comment by tataille** [comment]
Fix on main branch and version 1.2.7
